### ISSUE TITLE
Easing not found

### ISSUE THREAD

**Issue by anonymouz4** [xhamr/smooth-gradient#1]
There is not Easing Object

**Comment by warpling** [comment]
@xhamr the link in the README appears to be dead. I did find these which appear to be the same:
https://raw.githubusercontent.com/jesselucas/swift-easing/master/Easing.swift

**Comment by janselv** [comment]
the easing functions are up again, thanks for reporting it. 

PS: you don't need to pollute your project with all easing functions, just copy the file `EasingFunctions.swift` and the easing function that fit for you.

**Comment by warpling** [comment]
Thanks! Almost finished up writing my own in the meantime haha.
I think I'd be great if they were included in this project. I can't imagine why you'd want the CAGradientExtension without them?

**Comment by janselv** [comment]
I think you're right, I left then separated because once you select the right easing function the others are useless, but I'm refactoring the code and placing then together, you might come back a few minutes later for the updated version. ... again, thanks

**Comment by warpling** [comment]
Totally agree they're a bit of a mess but keeping them all in one file seems like a great move. I like to keep as many CAMediaTimingFunctions on hand so I can quickly tweak and find the right ones :)
